### ISSUE TITLE
node:12-puppeteer does not contain the Cloud SDK

### ISSUE THREAD

**Issue by averikitsch** [googleapis/testing-infra-docker#154]
docker image node:12-puppeteer, should have gcloud installed in order to work with `build-with-run.sh`

Error: https://fusion.corp.google.com/runanalysis/buildlogs/prod:cloud-devrel%2Fnodejs-docs-samples%2Fpresubmit%2Frun%2Fwebsockets/prod:cloud-devrel%2Fnodejs-docs-samples%2Fpresubmit%2Frun%2Fwebsockets/KOKORO/8e73f7b4-91b8-4ad7-af0e-0829f0c2cb66/1626985367760/build%20%23142/Targets

**Comment by kweinmeister** [comment]
This issue should now be obsolete, as we're no longer using the Node v12 puppeteer image. Please reopen if still needed.
